export const lobbyModes = [
  {
    id: "story",
    title: "Story",
    accent: "#ffb03a",
    secondaryAccent: "#ff6b2a",
    shadowColor: "#5f210a",
    scene: "story",
    narutoPose: "resolved",
    shortLabel: "Chronicle",
    background: {
      image: "/images/lobby-backdrop.png",
      objectPosition: "55% 45%",
      filter: "saturate(1.18) contrast(1.08) brightness(0.9)",
    },
    titleSize: "10.8rem",
    figureScale: "1.02",
  },
  {
    id: "adventure",
    title: "Adventure",
    accent: "#7ee85e",
    secondaryAccent: "#33d0a1",
    shadowColor: "#103a18",
    scene: "adventure",
    narutoPose: "stride",
    shortLabel: "Explore",
    background: {
      image: "/images/lobby-backdrop.png",
      objectPosition: "47% 45%",
      filter: "saturate(1.1) contrast(1.03) brightness(0.95) hue-rotate(36deg)",
    },
    titleSize: "8.8rem",
    figureScale: "0.98",
  },
  {
    id: "collection",
    title: "Collection",
    accent: "#58c9ff",
    secondaryAccent: "#4777ff",
    shadowColor: "#0d275f",
    scene: "collection",
    narutoPose: "focus",
    shortLabel: "Archive",
    background: {
      image: "/images/lobby-backdrop.png",
      objectPosition: "50% 50%",
      filter: "saturate(1.05) contrast(1.08) brightness(0.84) hue-rotate(170deg)",
    },
    titleSize: "8.4rem",
    figureScale: "0.96",
  },
  {
    id: "online-battle",
    title: "Online Battle",
    accent: "#a985ff",
    secondaryAccent: "#f36dff",
    shadowColor: "#27124e",
    scene: "online",
    narutoPose: "ready",
    shortLabel: "Network",
    background: {
      image: "/images/lobby-backdrop.png",
      objectPosition: "60% 47%",
      filter: "saturate(1.2) contrast(1.12) brightness(0.85) hue-rotate(232deg)",
    },
    titleSize: "7.8rem",
    figureScale: "1",
  },
  {
    id: "free-battle",
    title: "Free Battle",
    accent: "#ff496d",
    secondaryAccent: "#ff95ba",
    shadowColor: "#60101d",
    scene: "free",
    narutoPose: "strike",
    shortLabel: "Versus",
    background: {
      image: "/images/lobby-backdrop.png",
      objectPosition: "58% 52%",
      filter: "saturate(1.28) contrast(1.12) brightness(0.86) hue-rotate(-18deg)",
    },
    titleSize: "8.1rem",
    figureScale: "1.05",
  },
] as const;

export type LobbyMode = (typeof lobbyModes)[number];
export type LobbyModeId = LobbyMode["id"];
export type LobbyScene = LobbyMode["scene"];
export type NarutoPose = LobbyMode["narutoPose"];
