import type { IconType } from "react-icons";
import {
  SiCss,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFramer,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenapiinitiative,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiTailwindcss,
  SiTestinglibrary,
  SiTypescript,
  SiVercel,
} from "react-icons/si";

export type SkillItem = {
  id: string;
  title: string;
  icon: IconType;
  level: number;
  exp: number;
  color: string;
  glowColor: string;
};

export const skillsData = [
  {
    id: "javascript",
    title: "JavaScript",
    icon: SiJavascript,
    level: 92,
    exp: 88,
    color: "#f7df1e",
    glowColor: "rgba(247, 223, 30, 0.58)",
  },
  {
    id: "typescript",
    title: "TypeScript",
    icon: SiTypescript,
    level: 90,
    exp: 86,
    color: "#3178c6",
    glowColor: "rgba(49, 120, 198, 0.62)",
  },
  {
    id: "react",
    title: "React",
    icon: SiReact,
    level: 91,
    exp: 89,
    color: "#61dafb",
    glowColor: "rgba(97, 218, 251, 0.62)",
  },
  {
    id: "nextjs",
    title: "Next.js",
    icon: SiNextdotjs,
    level: 88,
    exp: 84,
    color: "#ffffff",
    glowColor: "rgba(255, 255, 255, 0.5)",
  },
  {
    id: "nodejs",
    title: "Node.js",
    icon: SiNodedotjs,
    level: 84,
    exp: 79,
    color: "#5fa04e",
    glowColor: "rgba(95, 160, 78, 0.58)",
  },
  {
    id: "express",
    title: "Express",
    icon: SiExpress,
    level: 80,
    exp: 73,
    color: "#f2f5f7",
    glowColor: "rgba(242, 245, 247, 0.44)",
  },
  {
    id: "html5",
    title: "HTML5",
    icon: SiHtml5,
    level: 96,
    exp: 94,
    color: "#e34f26",
    glowColor: "rgba(227, 79, 38, 0.62)",
  },
  {
    id: "css3",
    title: "CSS3",
    icon: SiCss,
    level: 94,
    exp: 91,
    color: "#1572b6",
    glowColor: "rgba(21, 114, 182, 0.62)",
  },
  {
    id: "tailwind",
    title: "Tailwind",
    icon: SiTailwindcss,
    level: 90,
    exp: 87,
    color: "#06b6d4",
    glowColor: "rgba(6, 182, 212, 0.62)",
  },
  {
    id: "git",
    title: "Git",
    icon: SiGit,
    level: 86,
    exp: 81,
    color: "#f05032",
    glowColor: "rgba(240, 80, 50, 0.62)",
  },
  {
    id: "github",
    title: "GitHub",
    icon: SiGithub,
    level: 84,
    exp: 78,
    color: "#f5f5f5",
    glowColor: "rgba(245, 245, 245, 0.46)",
  },
  {
    id: "rest-apis",
    title: "REST APIs",
    icon: SiOpenapiinitiative,
    level: 83,
    exp: 76,
    color: "#6ba539",
    glowColor: "rgba(107, 165, 57, 0.58)",
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    icon: SiPostgresql,
    level: 78,
    exp: 70,
    color: "#4169e1",
    glowColor: "rgba(65, 105, 225, 0.62)",
  },
  {
    id: "mongodb",
    title: "MongoDB",
    icon: SiMongodb,
    level: 76,
    exp: 68,
    color: "#47a248",
    glowColor: "rgba(71, 162, 72, 0.58)",
  },
  {
    id: "prisma",
    title: "Prisma",
    icon: SiPrisma,
    level: 74,
    exp: 65,
    color: "#2d3748",
    glowColor: "rgba(96, 131, 166, 0.5)",
  },
  {
    id: "docker",
    title: "Docker",
    icon: SiDocker,
    level: 72,
    exp: 62,
    color: "#2496ed",
    glowColor: "rgba(36, 150, 237, 0.62)",
  },
  {
    id: "vercel",
    title: "Vercel",
    icon: SiVercel,
    level: 82,
    exp: 75,
    color: "#ffffff",
    glowColor: "rgba(255, 255, 255, 0.48)",
  },
  {
    id: "playwright",
    title: "Playwright",
    icon: SiTestinglibrary,
    level: 72,
    exp: 63,
    color: "#2ead33",
    glowColor: "rgba(46, 173, 51, 0.58)",
  },
  {
    id: "figma",
    title: "Figma",
    icon: SiFigma,
    level: 77,
    exp: 69,
    color: "#a259ff",
    glowColor: "rgba(162, 89, 255, 0.62)",
  },
  {
    id: "ui-motion",
    title: "UI Motion",
    icon: SiFramer,
    level: 79,
    exp: 72,
    color: "#ff4f9a",
    glowColor: "rgba(255, 79, 154, 0.6)",
  },
] as const satisfies readonly SkillItem[];
